# Generated by Django 4.2.4 on 2023-08-20 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_blogcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
