# Generated by Django 4.2.4 on 2023-08-24 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_category_highlightpage_topicpage_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlightpage',
            options={'verbose_name': 'Highlight Page', 'verbose_name_plural': 'Highlight Pages'},
        ),
    ]
