# Generated by Django 4.2.4 on 2023-08-26 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_category_options_alter_blogpage_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnSportTopicPage',
            fields=[
                ('topicpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.topicpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.topicpage',),
        ),
    ]
