# Generated by Django 4.2.4 on 2023-08-27 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_categorygalleryimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryGalleryImage',
        ),
    ]
